# Generated by Django 5.2.8 on 2025-11-28 22:52

import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DeliveryAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_km', models.FloatField(help_text='Distance used for pay calculation (km).')),
                ('per_km_rate', models.DecimalField(decimal_places=2, help_text='Per km rate applied for this order.', max_digits=8)),
                ('distance_pay', models.DecimalField(decimal_places=2, help_text='distance_km * per_km_rate', max_digits=10)),
                ('bonus_amount', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Delivery Assignment',
                'verbose_name_plural': 'Delivery Assignments',
            },
        ),
        migrations.CreateModel(
            name='DriverProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicle_type', models.CharField(choices=[('bike', 'Bicycle'), ('car', 'Car')], max_length=10)),
                ('is_active', models.BooleanField(default=True, help_text='Whether the driver is active/onboarded on the platform.')),
                ('hourly_rate', models.DecimalField(decimal_places=2, default=Decimal('12.00'), help_text='Hourly pay in EUR.', max_digits=8)),
                ('per_km_rate', models.DecimalField(decimal_places=2, default=Decimal('0.15'), help_text='Per km pay in EUR, especially for bicycles.', max_digits=8)),
                ('service_area_city', models.CharField(blank=True, help_text='City where driver usually works.', max_length=100)),
                ('service_radius_km', models.FloatField(default=15.0, help_text="Max distance (km) for orders from driver's base.")),
                ('home_latitude', models.FloatField(blank=True, null=True)),
                ('home_longitude', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Driver Profile',
                'verbose_name_plural': 'Driver Profiles',
            },
        ),
        migrations.CreateModel(
            name='DriverShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField(blank=True, null=True)),
                ('total_minutes', models.PositiveIntegerField(blank=True, help_text='Computed when shift ends.', null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name': 'Driver Shift',
                'verbose_name_plural': 'Driver Shifts',
                'ordering': ['-start_time'],
            },
        ),
    ]
